name: flutter_advanced_networkimage
description: (fork) An advanced image provider provides caching and retrying for flutter app. Now with zoomable widget and transition to image widget.
version: 0.8.0
homepage: https://github.com/joaoricardobo/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  path_provider: ^1.6.11
  path: ^1.7.0
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.10.0 <3.0.0'
