name: flutter_advanced_networkimage
description: (fork) An advanced image provider provides caching and retrying for flutter app. Now with zoomable widget and transition to image widget.
version: 2.2.5
homepage: https://github.com/joaoricardobo/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  path_provider: ^2.0.2
  path: ^1.7.0
  flutter_svg: ^0.18.0
  pool: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.10.0 <3.0.0'
